config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#top"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :memos do
    collection do
      post :confirm
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :content, presence: true
  validates :content, length:{in:1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  
  def index
    @memos = Memo.all
  end
  
  def new
    @memo = Memo.new
  end
  
  def create
    @memo = Memo.create(memo_params)
    if @memo.save
      redirect_to memos_path,notice: "メモを作成しました"
    else
      render 'new'
    end
  end
  
  def edit
    @memo = Memo.find(params[:id])
  end
  
  def update
    @memo = Memo.find(params[:id])
    @memo.update(memo_params)
    redirect_to memos_path
  end
  
  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to memos_path
  end
  
  def confirm
    @memo = Memo.new(memo_params)
    render 'new' if @memo.invalid?
  end
  
  private
  def memo_params
    params.require(:memo).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/home/top.html.erb
<dl id="accordion">
  <dt>どういうもの？</dt>
  <dd>ちょっとしたメモを簡単に残しておくためのアプリ</dd>
  <dt>メモを書く</dt>
  <dd>残しておきたいメモを書いて保存を押します</dd>
  <dt>メモを見る</dt>
  <dd>残しておいたメモを見ることができます</dd>
  <dt>注意点</dt>
  <dd>課題の性質上、140文字以下までしかメモに残せません</dd>
</dl>

<script>
  $(function() {
  $('#accordion dd').hide();
  $('#accordion dt').click(function(){
    $(this).next('dd').slideToggle()
  })
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watepumemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="clearfix">
        <ul>
          <li class="header_navi"><%= link_to "Home" ,"/" %></li>
          <li class="header_navi"><%= link_to "メモを書く", new_memo_path %></li>
          <li class="header_navi"><%= link_to "メモを見る", memos_path %></li>
        </ul>
      </header>
      <div class="title">
        <h1>わてぷメモ</h1>
        <h2>学んだことを残しておくためのメモ</h2>
      </div>
      <main>
        <%= yield %>
      </main>
      <footer>
        <p>2018 わてぷメモ</p>
      </footer>
    </div>
  </body>
</html>

app/views/memos/confirm.html.erb
<h2>このメモを保存して良いですか？</h2>

<%= form_with(model: @memo, url: memos_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <div class="confirm_memo">
  <%= @memo.content %>
  </div>
  <div class="confirm_submit_btn">
  <%= form.submit "保存する", :class => "btn" %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h2>メモを書き換える</h2>

<%= form_with(model: @memo, local: true, :class => 'memo_title') do |form| %>

<div class="input_content">

  <%= form.text_area :content, :class => 'content_form' %>
  
  <div>
  <%= form.submit "書き換える", :class => "btn" %>
  </div>
<% end %>
</div>

app/views/memos/index.html.erb
<h2>メモ一覧</h2>



<table>
  <% @memos.each do |memo| %>
    <tr>
      <td><%= memo.content %></td>
    </tr>
    <tr>
      <td><%= link_to "メモの書き換え", edit_memo_path(memo.id),class: "edit_btn" %></td>
      <td><%= link_to "メモを捨てる", memo_path(memo.id),class: "delete_btn", method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/memos/new.html.erb
<h2>メモを書く</h2>
<%= form_with(model: @memo, local: true, :class => 'memo_title', url: confirm_memos_path) do |form| %>
  <% if @memo.errors.any? %>
  <div class="error_explanation">
    <h3 class="error_msg"><%= @memo.errors.count %>件のエラーがあります</h3>
    <ul>
      <% @memo.errors.full_messages.each do |msg| %>
      <li class="error_msg"><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<div class="input_content">

  <%= form.text_area :content, :class => 'content_form' %>
  
  <div>
  <%= form.submit "保存する", :class => "btn" %>
  </div>
<% end %>
</div>